"""VM — Virtual Machine for executing block plans.

Executes plans generated by the model. Plans are trees of blocks
with opcodes at the leaves. The VM traverses the tree, executes
opcodes, and returns results.
"""
