"""Special tokens for Za v6 plan/block/template system.

These tokens extend the base vocabulary with structural markers.
They are injected into training data and generated by the model.
"""

from __future__ import annotations

# Plan control tokens
PLAN_START = "[PLAN:"          # Start of plan: [PLAN:mode|steps=N|...]
PLAN_END = "[/PLAN]"           # End of plan

# Block tokens
BLOCK_START = "[BLOCK"         # Start of block: [BLOCK type=X id=Y]
BLOCK_END = "[/BLOCK]"         # End of block

# Template tokens
TMPL_START = "[TMPL:"          # Template reference: [TMPL:hash slot_0=val]
TMPL_END = "[/TMPL]"           # End of template expansion

# Slot tokens
ARG_TOKEN = "[ARG"             # Argument binding: [ARG field="value"]

# Create tokens
CREATE_TOKEN = "[CREATE:"      # Create new block: [CREATE:name|slots=N|from=...]

# Multi-level mask tokens
MASK_TOKEN = "[MASK]"          # Standard token mask (LLaDA)
MASK_SPAN = "[MASK_SPAN]"     # Span-level mask
MASK_SLOT = "[MASK_SLOT]"     # Slot-level mask
MASK_BLOCK = "[MASK_BLOCK]"   # Block-level mask
MASK_TEMPLATE = "[MASK_TMPL]"  # Template-level mask

# Meta tokens
META_THINK = "[THINK]"         # Allocate compute
META_REPLAN = "[REPLAN]"       # Request re-planning
META_ABORT = "[ABORT]"         # Abort execution

# All special tokens for tokenizer registration
SPECIAL_TOKENS = [
    PLAN_START, PLAN_END,
    BLOCK_START, BLOCK_END,
    TMPL_START, TMPL_END,
    ARG_TOKEN,
    CREATE_TOKEN,
    MASK_TOKEN, MASK_SPAN, MASK_SLOT, MASK_BLOCK, MASK_TEMPLATE,
    META_THINK, META_REPLAN, META_ABORT,
]

# Plan modes
PLAN_MODES = {
    "direct": 0,      # No computation needed
    "compute": 1,     # Simple opcode execution
    "pipeline": 2,    # Sequence of operations
    "retrieve": 3,    # Lookup from context/registry
    "compose": 4,     # Compose templates/blocks
}

# Block types for encoding
BLOCK_TYPES = {
    "token": 0,
    "span": 1,
    "template": 2,
    "plan": 3,
    "meta": 4,
}

# Complexity levels
COMPLEXITY_LEVELS = {
    "low": 0,
    "mid": 1,
    "high": 2,
}
